import { LegalList, LegalPage, LegalSection, LegalTerm } from '@/components/legal/LegalPage';
import { Card } from '@/components/ui';
import { SUPPORT_EMAIL } from '@/constants/disclosure';

/**
 * The Action Arena Privacy Policy.
 *
 * The copy is the published policy from web/legal/privacy.html, section for
 * section and sentence for sentence, so the app and the public site cannot
 * drift apart. Two placeholders in that file are resolved rather than printed:
 * `[CONTACT EMAIL]` becomes the support address the rest of the app already
 * uses, and the unset `[EFFECTIVE DATE]` line is left out instead of shipping a
 * literal bracket to players. Nothing else is added, cut or reworded.
 *
 * Mobile's /privacy shows the short PRIVACY_POLICY_DOCUMENT summary card —
 * that same summary is the intro paragraph below, with the full policy
 * underneath it, because a desktop browser has the room the phone did not.
 */
export function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Legal"
      intro="Action Arena uses account, league, pick, notification, and cosmetic data to operate the app experience. We do not sell personal data, and no real-money sports operator receives app data from Action Arena."
      title="Action Arena Privacy Policy">
      <Card className="border-electric-green/25 bg-electric-green/[0.06] p-6">
        <p className="text-sm font-semibold leading-7 text-white/75">
          Action Arena is a free-to-play fantasy sports prediction game. Coins, points, standings,
          and cosmetics are virtual and have no monetary value. No real money is paid, won, or
          redeemable inside the app, and there are no redemption features or links to real-money
          sports operators.
        </p>
      </Card>

      <LegalSection title="Data We Collect">
        <p>
          We collect only the data needed to create accounts, run leagues, show picks and standings,
          deliver optional notifications, and manage Season Pass access.
        </p>
        <LegalList>
          <li>
            <LegalTerm>Contact Info:</LegalTerm> email address for Supabase email authentication,
            sign-in, account recovery, and account management.
          </li>
          <li>
            <LegalTerm>Identifiers:</LegalTerm> your Supabase user ID and authentication session
            identifiers. If you enable notifications, we may store an Expo push notification token
            tied to your account so app notifications can be delivered.
          </li>
          <li>
            <LegalTerm>Account and profile data:</LegalTerm> display name, avatar URL, Arena Coins
            balance, notification preferences, equipped cosmetics, and related account settings.
          </li>
          <li>
            <LegalTerm>User Content:</LegalTerm> league names and descriptions you create, team
            names, league membership, chat messages, stickers, shared picks, content reports,
            blocked-user records, and gameplay content such as picks, bet legs, matchup results,
            standings, achievements, and season history.
          </li>
          <li>
            <LegalTerm>Purchases:</LegalTerm> Season Pass entitlement status, season year, source,
            and Apple in-app purchase validation metadata such as product ID, transaction ID,
            original transaction ID, Apple purchase date, Apple receipt validation environment, and
            receipt validation time.
          </li>
          <li>
            <LegalTerm>Gameplay data:</LegalTerm> league settings, invite codes, weekly cards, pick
            amounts, odds, selections, results, profits, standings, matchups, leaderboard
            information, cosmetics purchases using virtual Arena Coins, and notification events
            generated by app activity.
          </li>
        </LegalList>
      </LegalSection>

      <LegalSection title="App Store Privacy Labels">
        <p>
          The App Store privacy labels for Action Arena are intended to match the current app
          behavior:
        </p>
        <div className="overflow-x-auto">
          <table className="w-full min-w-[32rem] border-collapse text-left text-sm">
            <thead>
              <tr className="border-b border-border">
                <th className="py-2 pr-4 text-[11px] font-black uppercase tracking-[0.1em] text-white/50">
                  Data Type
                </th>
                <th className="py-2 pr-4 text-[11px] font-black uppercase tracking-[0.1em] text-white/50">
                  Linked to You
                </th>
                <th className="py-2 text-[11px] font-black uppercase tracking-[0.1em] text-white/50">
                  Purpose
                </th>
              </tr>
            </thead>
            <tbody>
              {[
                ['Email Address (Contact Info)', 'Yes', 'App functionality and account management'],
                ['User Content', 'Yes', 'App functionality and account management'],
                ['User ID (Identifiers)', 'Yes', 'App functionality and account management'],
                ['Purchases', 'Yes', 'App functionality and account management'],
              ].map(([dataType, linked, purpose]) => (
                <tr className="border-b border-border/60 last:border-0" key={dataType}>
                  <td className="py-2 pr-4 font-bold text-white">{dataType}</td>
                  <td className="py-2 pr-4 font-semibold text-electric-green">{linked}</td>
                  <td className="py-2 text-white/70">{purpose}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p>
          Action Arena does not use this data for advertising, third-party tracking, or sale of
          data.
        </p>
      </LegalSection>

      <LegalSection title="How We Use Data">
        <LegalList>
          <li>To create, authenticate, recover, and manage your account.</li>
          <li>
            To let you create and join leagues, submit picks, view matchups, chat with league
            members, and see standings, achievements, cosmetics, and profile stats.
          </li>
          <li>
            To enforce gameplay rules, moderate objectionable content, process reports and blocks,
            and protect league integrity.
          </li>
          <li>
            To deliver optional push notifications for league activity, pick reminders, results,
            awards, and similar app functionality.
          </li>
          <li>To verify, restore, and maintain your Season Pass entitlement.</li>
          <li>To troubleshoot app functionality and maintain service reliability.</li>
        </LegalList>
      </LegalSection>

      <LegalSection title="Storage and Security">
        <p>
          Action Arena stores account, league, pick, standings, notification, cosmetic, moderation,
          and Season Pass entitlement data in Supabase. Supabase provides authentication, database
          storage, row-level security, realtime updates, and server-side Edge Functions used by the
          app. Authentication sessions are stored on your device so you can stay signed in.
        </p>
        <p>
          We use access controls so users can access the app data needed for their own account and
          leagues. No method of storage or transmission is perfectly secure, but we use Supabase
          security features and app-level authorization rules to limit access to personal data.
        </p>
      </LegalSection>

      <LegalSection title="In-App Purchases">
        <p>
          Apple processes payment for the Season Pass through Apple In-App Purchase. Action Arena
          does not receive your full payment card details. To unlock or restore the Season Pass, the
          app sends Apple receipt data and related transaction identifiers to a Supabase Edge
          Function, which validates the receipt with Apple and stores the resulting Season Pass
          entitlement in Supabase.
        </p>
        <p>
          The Season Pass unlocks premium extras such as exclusive cosmetics, advanced analytics,
          early Pick Board access when configured, and future ad-free hooks. Core gameplay remains
          free, and Action Arena does not offer real-money wagering, cash-out, or redemption
          features.
        </p>
      </LegalSection>

      <LegalSection title="Analytics and Crash Reporting">
        <p>
          The current app does not include a third-party analytics SDK or crash-reporting SDK.
          Development builds include lightweight console logging for typed app events such as
          league creation, chat messages, cosmetic actions, and Season Pass actions. Those console
          logs are for development troubleshooting and are not used for advertising or third-party
          tracking.
        </p>
      </LegalSection>

      <LegalSection title="Data Retention and Account Deletion">
        <p>
          We retain account and gameplay data while your account is active so leagues, standings,
          picks, chat, notifications, cosmetics, and Season Pass entitlements can function. Some
          league history may remain where needed to preserve league records, enforce moderation
          decisions, or comply with legal, security, or operational requirements.
        </p>
        <p>
          You can delete your account in the app by opening Settings and choosing Delete Account.
          The app sends an authenticated deletion request to Supabase, deletes the Supabase Auth
          user, signs you out locally, and clears local cached app data. Database records tied to
          your user ID are deleted or cleaned up according to the app's Supabase deletion rules,
          including account, league membership, pick, standings, notification, cosmetic, chat, and
          Season Pass records that are linked to the deleted user.
        </p>
        <p>
          If you cannot access the app, contact us at {SUPPORT_EMAIL} and include the email address
          on the account you want deleted.
        </p>
      </LegalSection>

      <LegalSection title="Children">
        <p>
          Action Arena is not directed to children. Because the app is a simulated sports prediction
          game with a simulated-gambling age rating, it is intended for users old enough to use apps
          with that rating in their region. We do not knowingly collect personal data from children.
        </p>
      </LegalSection>

      <LegalSection title="No Sale of Data, Ads, or Tracking">
        <p>
          We do not sell personal data. We do not use personal data for advertising. We do not share
          app data with real-money sports operators. We do not use third-party tracking for
          advertising or cross-app tracking.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          Questions about this Privacy Policy, support, or account deletion can be sent to{' '}
          <a
            className="font-bold text-electric-green hover:underline"
            href={`mailto:${SUPPORT_EMAIL}`}>
            {SUPPORT_EMAIL}
          </a>
          .
        </p>
      </LegalSection>
    </LegalPage>
  );
}
